sudo: required
language: node_js
node_js:
- node
services:
- docker
before_install:
- set -e
- docker pull justinribeiro/chrome-headless
- docker run -d --net host justinribeiro/chrome-headless
- docker ps -a
install:
- npm install
script:
- npm run ci:lint
- npm run ci:test
- BUILD_ID=$TRAVIS_BUILD_ID BUILD_SYSTEM=travisci npm start
after_success:
- npm run ci:send-coverage
